// The rules, the dictionary and the ghosts, without a page:  node --test test/unit.test.mjs
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import * as dict from '../js/dict.js';
import * as R from '../js/rules.js';
import { GHOSTS, ghostById, chooseMove, nameWord } from '../js/ghosts.js';
import { encode, decode } from '../js/packed.js';

await dict.loadMore();

// A tiny random number generator, so the ghost games come out the same every run.
function seeded(seed) {
  let a = seed;
  return () => { a |= 0; a = a + 0x6D2B79F5 | 0; let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; };
}

const two = (a = { kind: 'person', name: 'You' }, b = { kind: 'ghost', ghost: 'wisp', name: 'Wisp' }) => R.newGame([a, b]);
const play = (s, letters) => [...letters].reduce((st, c) => R.addLetter(st, c, dict.endsRound), s);

test('front coding round-trips', () => {
  const words = ['ghost', 'ghostly', 'ghosts', 'ghoul', 'goblin'];
  assert.deepEqual(decode(encode(words)), words);
});

test('the round-ending words: four letters or more, and only ones you can reach', () => {
  assert.ok(dict.endsRound('ghost'));
  assert.ok(dict.endsRound('play'));
  assert.equal(dict.endsRound('cat'), 0, 'three-letter words never end a round');
  assert.equal(dict.nodeAt('player'), null, 'the round ends at play, so player is never reached');
  assert.equal(dict.endsRound('ghos'), 0);
});

test('naming a word: rare words count, and so do words past a shorter one', () => {
  assert.ok(dict.isWord('ghostly'), 'longer than ghost, but still a word');
  assert.ok(dict.isWord('player'));
  assert.ok(dict.isWord('qoph'), 'a Scrabble word from the big list');
  assert.ok(!dict.isWord('ghostz'));
  assert.ok(!dict.isWord('cat'), 'too short');
  assert.ok(dict.anyWordStarts('xylo'));
  assert.ok(!dict.anyWordStarts('qx'));
});

test('an example word is short and common', () => {
  assert.equal(dict.exampleWord('gho'), 'ghost');
  assert.equal(dict.exampleWord('qx'), null);
});

test('word list files are generated and complete', async () => {
  const ends = await readFile(new URL('../js/words-ends.js', import.meta.url), 'utf8');
  assert.match(ends, /Generated by tools\/build-words\.mjs/);
  let count = 0;
  (function walk(n) { if (n.e) count++; for (const c in n.k) walk(n.k[c]); })(dict.root);
  assert.ok(count > 15000, `only ${count} round-ending words`);
});

test('spelling a word ends the round, and the speller takes a letter', () => {
  let s = two();
  s = play(s, 'ghos');
  assert.equal(s.phase, 'play');
  assert.equal(s.turn, 0);
  s = R.addLetter(s, 't', dict.endsRound);
  assert.equal(s.phase, 'over');
  assert.equal(s.result.why, 'spelled');
  assert.equal(s.result.loser, 0);
  assert.equal(s.players[0].letters, 1);
  s = R.nextRound(s);
  assert.equal(s.frag, '');
  assert.equal(s.turn, 0, 'the loser starts the next round');
  assert.equal(s.round, 2);
});

test('challenges: a named word beats the challenge, giving up loses', () => {
  let s = play(two(), 'gh');
  assert.ok(R.canChallenge(s));
  s = R.challenge(s);
  assert.equal(s.phase, 'naming');
  assert.deepEqual([s.challenge.by, s.challenge.of], [0, 1]);
  const failed = R.nameWord(s, 'ghostly', true);
  assert.equal(failed.result.loser, 0, 'the challenger loses when a word is named');
  const wrong = R.nameWord(s, 'ghzz', false);
  assert.equal(wrong.phase, 'naming', 'a word that doesn’t count can be fixed');
  assert.equal(wrong.challenge.wrong, 'ghzz');
  const bluff = R.giveUp(wrong);
  assert.equal(bluff.result.loser, 1);
  assert.equal(bluff.result.why, 'bluff');
});

test('you can’t challenge a single letter, or yourself', () => {
  const s = play(two(), 'g');
  assert.ok(!R.canChallenge(s));
  assert.equal(R.challenge(s), s);
});

test('five letters and you are out; the last one left wins', () => {
  let s = R.newGame([{ kind: 'person', name: 'A' }, { kind: 'person', name: 'B' }, { kind: 'ghost', ghost: 'maud', name: 'Maud' }]);
  s = { ...s, players: s.players.map((p, i) => (i === 1 ? { ...p, letters: 4 } : p)) };
  s = play(s, 'ghost'); // A g, B h, Maud o, A s, B t
  assert.equal(s.result.loser, 1);
  assert.equal(s.phase, 'over', 'two players are still in');
  s = R.nextRound(s);
  assert.equal(s.turn, 2, 'B is out, so the next player starts');
  assert.equal(R.nextIn(s, 2), 0, 'and B is skipped');
  s = { ...s, turn: 0, players: s.players.map((p, i) => (i === 0 ? { ...p, letters: 4 } : p)) };
  s = play(s, 'ghost'); // A g, Maud h, A o, Maud s, A t
  assert.equal(s.phase, 'done');
  assert.equal(s.winner, 2);
});

test('the game ends when the people are all out, even with ghosts left', () => {
  let s = R.newGame([{ kind: 'person', name: 'You' }, { kind: 'ghost', ghost: 'wisp', name: 'Wisp' }, { kind: 'ghost', ghost: 'maud', name: 'Maud' }]);
  s = { ...s, players: s.players.map((p, i) => (i === 0 ? { ...p, letters: 4 } : p)) };
  s = play(s, 'play'); // You p, Wisp l, Maud a, You y
  assert.equal(s.result.loser, 0);
  assert.equal(s.phase, 'done');
  assert.equal(s.winner, -1, 'only ghosts are left');
});

test('ghosts challenge letters that can’t become a word', () => {
  const s = play(two(), 'qx');
  for (const g of GHOSTS) assert.deepEqual(chooseMove(g, { ...s, turn: 1, last: 0 }, seeded(1)), { challenge: true }, g.name);
});

test('ghosts never spell a word when there’s a safe letter', () => {
  const rnd = seeded(7);
  for (const frag of ['', 'g', 'gh', 'ghos', 'pla', 'qui', 'zeb', 'tran']) {
    for (const g of GHOSTS) {
      for (let k = 0; k < 10; k++) {
        const s = { ...play(two(), frag), turn: 1, last: frag ? 0 : -1 };
        const move = chooseMove(g, s, rnd);
        if (move.challenge) { assert.ok(frag.length >= 2); continue; }
        const next = frag + move.letter;
        const node = dict.nodeAt(frag);
        const hasSafe = node && Object.values(node.k).some(n => !n.e && n.r & g.knows);
        if (hasSafe) assert.equal(dict.endsRound(next), 0, `${g.name} spelled ${next}`);
      }
    }
  }
});

test('a challenged ghost names a real word, or owns up to a bluff', () => {
  for (const g of GHOSTS) {
    const w = nameWord(g, 'gho', {});
    assert.ok(w && w.startsWith('gho') && dict.isWord(w), `${g.name} named ${w}`);
    assert.equal(nameWord(g, 'gho', { bluff: true }), null);
  }
  assert.ok(dict.isWord(nameWord(ghostById('hollis'), 'mho', { rare: true })), 'Hollis can back up a rare word');
});

test('the hard ghost beats the easy one, and the easy one is beatable', () => {
  const rnd = seeded(42);
  const wins = { wisp: 0, hollis: 0 };
  for (let game = 0; game < 12; game++) {
    const order = game % 2 ? ['wisp', 'hollis'] : ['hollis', 'wisp'];
    let s = R.newGame(order.map(id => ({ kind: 'person', ghost: id, name: id })));
    for (let steps = 0; s.phase !== 'done' && steps < 2000; steps++) {
      if (s.phase === 'over') { s = R.nextRound(s); continue; }
      if (s.phase === 'play') {
        const m = chooseMove(ghostById(s.players[s.turn].ghost), s, rnd);
        s = m.challenge ? R.challenge(s) : R.addLetter(s, m.letter, dict.endsRound, m.bluff ? { bluff: true } : {});
      } else {
        const w = nameWord(ghostById(s.players[s.challenge.of].ghost), s.frag, s.moves.at(-1));
        s = w ? R.nameWord(s, w, dict.isWord(w)) : R.giveUp(s);
      }
    }
    wins[s.players[s.winner].ghost]++;
  }
  assert.ok(wins.hollis >= 10, `Hollis won ${wins.hollis} of 12`);
});
